#{% set version = "2.7.2" %}
{% set data = load_setup_py_data() %}

package:
  name: openalea.lpy
  version: {{ data.get('version') }}

source:
  path: ..

about:
  home: https://github.com/openalea/lpy
  license: Cecill-C
  summary: L-Py is a simulation software that mixes L-systems construction with the Python high-level modeling language.

build:
  preserve_egg_dir: True
  number: 0
requirements:
  build:
    - binutils_impl_linux-64<2.31.0 # [linux]
    - {{ compiler('cxx') }}
    - python {{PY_VER}}
    - cmake >=3.12.0
    - pkg-config                        # [linux]
    - make                              # [unix]
    - menuinst                          # [win]
  host:
    - python {{PY_VER}}
    - setuptools
    - openalea.plantgl
    # - boost # provided by plantgl
    - pyqt
  run:
    - python {{PY_VER}}
    - setuptools
    - {{ pin_compatible('openalea.plantgl', max_pin='x.x') }} 
    - {{ pin_compatible('boost',            max_pin='x.x.x') }} 
    - pyqt
    - ipython
    - qtconsole
    - jupyter_client <6
    - pyopengl
    - pyqglviewer

test:
  requires:
    - nose
  imports:
    - openalea.lpy
  source_files:
    - test/
    - share/
  commands:
    - nosetests -v -I test_predecessor_at_scale.py -I test_ui.py [unix]
    - nosetests -v -I test_predecessor_at_scale.py -I test_ui.py -I test_axialtree.py -I test_successor_at_scale.py [win]
